"""empty message

Revision ID: 82fd92c7bed5
Revises: 1e2757a7e72c
Create Date: 2022-05-07 11:16:25.326664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fd92c7bed5'
down_revision = '1e2757a7e72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('captche', table_name='email_captcha')
    op.create_unique_constraint(None, 'email_captcha', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_captcha', type_='unique')
    op.create_index('captche', 'email_captcha', ['captcha'], unique=False)
    op.drop_table('user')
    # ### end Alembic commands ###
